name: ci
on:
  push:
    branches: [ "main" ]
jobs:
  build_lin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build apps
        run: make
  build_win:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build apps
        run: make
  build_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build apps
        run: make
  tests:
    runs-on: ubuntu-latest
    needs: build_lin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: build apps
        run: make
      - name: test app
        run: pytest -s "integration tests/pythonProject/"
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: build apps
        run: make
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}
      - name: Copy files to server
        run: |
          gcloud compute scp ./grep/s21_grep ./cat/s21_cat user@instance-20240919-183243:~/ --zone="us-central1-f"
