name: ci
on:
  push:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug directory
        run: ls -al
      
      - name: build
        run: make test
